### ISSUE TITLE
Artisan breaks when no app key is set

### ISSUE THREAD

**Issue by DuckThom** [Snowfire/Beautymail#57]
When the service provider `Snowfire\Beautymail\BeautymailServiceProvider::class` is set in `config/app.php`, running any artisan command will result in the following error if the app key has not been set yet.

```
PHP Fatal error:  Uncaught RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:29
Stack trace:
#0 /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('encrypter')
#4 /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(173): Illuminate\Container\C in /var/www/laravel-wtg/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php on line 29
```

After removing the service provider from the list, artisan started working again.

Laravel: 5.1
PHP: 7.0 and 7.1

**Comment by emilsundberg** [comment]
Do you have a key specified in `config/app.php`/`.env`?

**Comment by DuckThom** [comment]
I did some research and the following line in the server provider is causing the issue.

`$this->app['mailer']->getSwiftMailer()->registerPlugin(new CssInlinerPlugin());`

I do not have an app key set yet as it's a fresh clone of a laravel app.
But because the service provider is already in `config/app.php` I am not able to generate one either with `php artisan key:generate` due to the error.

**Comment by DuckThom** [comment]
A fix would be to wrap that line in a `try catch` like this:

```
try {
            $this->app['mailer']->getSwiftMailer()->registerPlugin(new CssInlinerPlugin());
        } catch (\Exception $e) {
            \Log::debug('Skipped registering SwiftMailer plugin: CssInlinerPlugin.');
        }
```
